### ISSUE TITLE
Server answered with error:unable to find IS as"Network::Interface::L3Base"

### ISSUE THREAD

**Issue by hasantahsindagli** [zenden2k/KeeneticRainmeterPlugin#1]
Hi,

I read your descriptions and learned the ISP name. But I cannot see my download and sending speeds in any way. I get this error in the Log section from Rainmeter. I'll be happy if you can help me.

PS:I have Keenetic Hero DSL
![14 09 2023 - 18 12 41-New Issue · zenden2k_KeeneticRainmeterPlugin — Mozilla Firefox](https://github.com/zenden2k/KeeneticRainmeterPlugin/assets/62343087/c21c47e7-ad55-4cc9-98f5-7ae53f8a1191)
![14 09 2023 - 18 13 24-C__WINDOWS_system32_cmd exe](https://github.com/zenden2k/KeeneticRainmeterPlugin/assets/62343087/b476f611-4e2b-4fd5-93e2-3a702895e160)

**Comment by zenden2k** [comment]
You should use "DSL" as interface name in Rainmeter.data
If you have already put DSL in there but still getting "unable ot find ISP", it means that RainMeter cannot read your configuration file and is using default value.

```
[KeeneticPlugin]
Login=admin
Password=qwerty1234
URL=http://192.168.1.1
Interface=DSL
```

**Comment by hasantahsindagli** [comment]
> You should use "DSL" as interface name in Rainmeter.data If you already put DSL in there but still getting "unable ot find ISP", it means that RainMeter cannot read your configuration file and using default value.
> 
> ```
> [KeeneticPlugin]
> Login=admin
> Password=qwerty1234
> URL=http://192.168.1.1
> Interface=DSL
> ```

Sorry, my fault. I forgot to do this part. Currently working. Thank you :)
